
# Cptcode.create!([{:cpt_code => '0003T', :cpt_description => 'Cervicography', :cpt_price => 110},
#                 {:cpt_code => '0008T', :cpt_description => 'Upper gi endoscopy w/suture', :cpt_price => 120},
#                 {:cpt_code => '0010T', :cpt_description => 'Tb test, gamma interferon', :cpt_price => 130},
#                 {:cpt_code => '0016T', :cpt_description => 'Thermotx choroid vasc lesion', :cpt_price => 140},
#                 {:cpt_code => '0017T', :cpt_description => 'Photocoagulat macular drusen', :cpt_price => 150},
#                 {:cpt_code => '0018T', :cpt_description =>	'Transcranial magnetic stimul', :cpt_price =>160},
#                 {:cpt_code => '0019T', :cpt_description => 'Extracorp shock wave tx, ms', :cpt_price => 170},
#                 {:cpt_code => '0020T', :cpt_description => 'Extracorp shock wave tx, ft', :cpt_price =>180},
#                 {:cpt_code => '0021T', :cpt_description => 'Fetal oximetry, trnsvag/cerv', :cpt_price =>190},
#                 {:cpt_code => '0023T', :cpt_description => 'Phenotype drug test, hiv 1', :cpt_price =>200},
#                 {:cpt_code => '0024T', :cpt_description => 'Transcath cardiac reduction', :cpt_price =>300},
#                 {:cpt_code => '0026T', :cpt_description => 'Measure remnant lipoproteins', :cpt_price =>500},
#                 {:cpt_code => '0027T', :cpt_description => 'Endoscopic epidural lysis', :cpt_price =>101},
#                 {:cpt_code => '0028T', :cpt_description => 'Dexa body composition study', :cpt_price =>102},
#                 {:cpt_code => '0029T', :cpt_description => 'Magnetic tx for incontinence', :cpt_price =>103},
#                 {:cpt_code => '0030T', :cpt_description => 'Antiprothrombin antibody', :cpt_price =>104},
#                 {:cpt_code => '0031T', :cpt_description => 'Speculoscopy', :cpt_price =>105},
#                 {:cpt_code => '0032T', :cpt_description => 'Speculoscopy w/direct sample', :cpt_price =>106},
#                 {:cpt_code => '0033T', :cpt_description => 'Endovasc taa repr incl subcl', :cpt_price =>107},
#                 {:cpt_code => '0034T', :cpt_description => 'Endovasc taa repr w/o subcl', :cpt_price =>108},
#                 {:cpt_code => '0035T', :cpt_description => 'Insert endovasc prosth, taa', :cpt_price =>109},
#                 {:cpt_code => '0036T', :cpt_description => 'Endovasc prosth, taa, add-on', :cpt_price =>110},
#                 {:cpt_code => '0037T', :cpt_description => 'Artery transpose/endovas taa', :cpt_price =>120},
#                 {:cpt_code => '0038T', :cpt_description => 'Rad endovasc taa rpr w/cover', :cpt_price =>130},
#                 {:cpt_code => '0039T', :cpt_description => 'Rad s/i, endovasc taa repair', :cpt_price =>140},
#                 {:cpt_code => '0040T', :cpt_description => 'Rad s/i, endovasc taa prosth', :cpt_price =>150},
#                 {:cpt_code => '0041T', :cpt_description => 'Detect ur infect agnt w/cpas', :cpt_price =>160},
#                 {:cpt_code => '0042T', :cpt_description => 'Ct perfusion w/contrast, cbf', :cpt_price =>170},
#                 {:cpt_code => '0043T', :cpt_description => 'Co expired gas analysis', :cpt_price =>210},
#                 {:cpt_code => '0044T', :cpt_description => 'Whole body photography', :cpt_price =>111},
#                 {:cpt_code => '0045T', :cpt_description => 'Whole body photography', :cpt_price =>112},
#                 {:cpt_code => '0046T', :cpt_description => 'Cath lavage, mammary duct(s', :cpt_price =>113},
#                 {:cpt_code => '0047T', :cpt_description => 'Cath lavage, mammary duct(s)', :cpt_price =>115},
#                 {:cpt_code => '0048T', :cpt_description => 'Implant ventricular device', :cpt_price =>116},
#                 {:cpt_code => '0049T', :cpt_description => 'External circulation assist', :cpt_price =>117},
#                 {:cpt_code => '0050T', :cpt_description => 'Removal circulation assist', :cpt_price =>118},
#                 {:cpt_code => '0051T', :cpt_description => 'Implant total heart system', :cpt_price =>119},
#                 {:cpt_code => '0052T', :cpt_description => 'Replace component heart syst', :cpt_price =>120},
#                 {:cpt_code => '0053T', :cpt_description => 'Replace component heart syst', :cpt_price =>121},
#                 {:cpt_code => '0054T', :cpt_description => 'Bone surgery using computer', :cpt_price =>122}]);

# # seed icd_codes table
# Icdcode.create!([
#               {:category_code => 'A00', :diagnosis_code => '0',:FULL_CODE => 'A000',:abbreviated_description => 'Cholera due to Vibrio cholerae 01, biovar cholerae',:full_description => 'Cholera due to Vibrio cholerae 01, biovar cholerae',:category_title => 'Cholera'},
#               {:category_code => 'A00', :diagnosis_code => '1',:FULL_CODE => 'A001',:abbreviated_description => 'Cholera due to Vibrio cholerae 01, biovar eltor',:full_description => 'Cholera due to Vibrio cholerae 01, biovar eltor',:category_title => 'Cholera'},
#               {:category_code => 'A00', :diagnosis_code => '9',:FULL_CODE => 'A009',:abbreviated_description => 'Cholera, unspecified',:full_description => 'Cholera, unspecified',:category_title => 'Cholera'},
#               {:category_code => 'A010', :diagnosis_code => '0', :FULL_CODE => 'A0100', :abbreviated_description => 'Typhoid fever, unspecified', :full_description => 'Typhoid fever, unspecified', :category_title => 'Typhoid fever'},
#               {:category_code => 'A010', :diagnosis_code => '1', :FULL_CODE => 'A0101', :abbreviated_description => 'Typhoid meningitis', :full_description => 'Typhoid meningitis', :category_title => 'Typhoid fever'},
#               {:category_code => 'A010', :diagnosis_code => '2', :FULL_CODE => 'A0102', :abbreviated_description => 'Typhoid fever with heart involvement', :full_description => 'Typhoid fever with heart involvement', :category_title => 'Typhoid fever'},
#               {:category_code => 'A010', :diagnosis_code => '3', :FULL_CODE => 'A0103', :abbreviated_description => 'Typhoid pneumonia', :full_description => 'Typhoid pneumonia', :category_title => 'Typhoid fever'},
#               {:category_code => 'A010', :diagnosis_code => '4', :FULL_CODE => 'A0104', :abbreviated_description => 'Typhoid arthritis', :full_description => 'Typhoid arthritis', :category_title => 'Typhoid fever'},
#               {:category_code => 'A010', :diagnosis_code => '5', :FULL_CODE => 'A0105', :abbreviated_description => 'Typhoid osteomyelitis', :full_description => 'Typhoid osteomyelitis', :category_title => 'Typhoid fever'},
#               {:category_code => 'A010', :diagnosis_code => '9', :FULL_CODE => 'A0109', :abbreviated_description => 'Typhoid fever with other complications', :full_description => 'Typhoid fever with other complications', :category_title => 'Typhoid fever'},
#               {:category_code => 'A011', :diagnosis_code => '', :FULL_CODE => 'A011', :abbreviated_description => 'Paratyphoid fever A', :full_description => 'Paratyphoid fever A', :category_title => 'Paratyphoid fever A'},
#               {:category_code => 'A012', :diagnosis_code => '', :FULL_CODE => 'A012', :abbreviated_description => 'Paratyphoid fever B', :full_description => 'Paratyphoid fever B', :category_title => 'Paratyphoid fever B'},
#               {:category_code => 'A013', :diagnosis_code => '', :FULL_CODE => 'A013', :abbreviated_description => 'Paratyphoid fever C', :full_description => 'Paratyphoid fever C', :category_title => 'Paratyphoid fever C'},
#               {:category_code => 'A014', :diagnosis_code => '', :FULL_CODE => 'A014', :abbreviated_description => 'Paratyphoid fever, unspecified', :full_description => 'Paratyphoid fever, unspecified', :category_title => 'Paratyphoid fever, unspecified'},
#               {:category_code => 'A02', :diagnosis_code => '0', :FULL_CODE => 'A020', :abbreviated_description => 'Salmonella enteritis', :full_description => 'Salmonella enteritis', :category_title => 'Other salmonella infections'},
#               {:category_code => 'A02', :diagnosis_code => '1', :FULL_CODE => 'A021', :abbreviated_description => 'Salmonella sepsis', :full_description => 'Salmonella sepsis', :category_title => 'Other salmonella infections'},
#               {:category_code => 'A022', :diagnosis_code => '0', :FULL_CODE => 'A0220', :abbreviated_description => 'Localized salmonella infection, unspecified', :full_description => 'Localized salmonella infection, unspecified', :category_title => 'Localized salmonella infections'},
#               {:category_code => 'A022', :diagnosis_code => '1', :FULL_CODE => 'A0221', :abbreviated_description => 'Salmonella meningitis', :full_description => 'Salmonella meningitis', :category_title => 'Localized salmonella infections'},
#               {:category_code => 'A022', :diagnosis_code => '2', :FULL_CODE => 'A0222', :abbreviated_description => 'Salmonella pneumonia', :full_description => 'Salmonella pneumonia', :category_title => 'Localized salmonella infections'},
#               {:category_code => 'A022', :diagnosis_code => '3', :FULL_CODE => 'A0223', :abbreviated_description => 'Salmonella arthritis', :full_description => 'Salmonella arthritis', :category_title => 'Localized salmonella infections'},
#               {:category_code => 'A022', :diagnosis_code => '4', :FULL_CODE => 'A0224', :abbreviated_description => 'Salmonella osteomyelitis', :full_description => 'Salmonella osteomyelitis', :category_title => 'Localized salmonella infections'},
#               {:category_code => 'A022', :diagnosis_code => '5', :FULL_CODE => 'A0225', :abbreviated_description => 'Salmonella pyelonephritis', :full_description => 'Salmonella pyelonephritis', :category_title => 'Localized salmonella infections'},
#               {:category_code => 'A022', :diagnosis_code => '9', :FULL_CODE => 'A0229', :abbreviated_description => 'Salmonella with other localized infection', :full_description => 'Salmonella with other localized infection', :category_title => 'Localized salmonella infections'},
#               {:category_code => 'A028', :diagnosis_code => '', :FULL_CODE => 'A028', :abbreviated_description => 'Other specified salmonella infections', :full_description => 'Other specified salmonella infections', :category_title => 'Other specified salmonella infections'},
#               {:category_code => 'A029', :diagnosis_code => '', :FULL_CODE => 'A029', :abbreviated_description => 'Salmonella infection, unspecified', :full_description => 'Salmonella infection, unspecified', :category_title => 'Salmonella infection, unspecified'},
#               {:category_code => 'A03', :diagnosis_code => '0', :FULL_CODE => 'A030', :abbreviated_description => 'Shigellosis due to Shigella dysenteriae', :full_description => 'Shigellosis due to Shigella dysenteriae', :category_title => 'Shigellosis'},
#               {:category_code => 'A03', :diagnosis_code => '1', :FULL_CODE => 'A031', :abbreviated_description => 'Shigellosis due to Shigella flexneri', :full_description => 'Shigellosis due to Shigella flexneri', :category_title => 'Shigellosis'},
#               {:category_code => 'A03', :diagnosis_code => '2', :FULL_CODE => 'A032', :abbreviated_description => 'Shigellosis due to Shigella boydii', :full_description => 'Shigellosis due to Shigella boydii', :category_title => 'Shigellosis'},
#               {:category_code => 'A03', :diagnosis_code => '3', :FULL_CODE => 'A033', :abbreviated_description => 'Shigellosis due to Shigella sonnei', :full_description => 'Shigellosis due to Shigella sonnei', :category_title => 'Shigellosis'},
#               {:category_code => 'A03', :diagnosis_code => '8', :FULL_CODE => 'A038', :abbreviated_description => 'Other shigellosis', :full_description => 'Other shigellosis', :category_title => 'Shigellosis'},
#               {:category_code => 'A03', :diagnosis_code => '9', :FULL_CODE => 'A039', :abbreviated_description => 'Shigellosis, unspecified', :full_description => 'Shigellosis, unspecified', :category_title => 'Shigellosis'},
#               {:category_code => 'A04', :diagnosis_code => '0', :FULL_CODE => 'A040', :abbreviated_description => 'Enteropathogenic Escherichia coli infection', :full_description => 'Enteropathogenic Escherichia coli infection', :category_title => 'Other bacterial intestinal infections'},
#               {:category_code => 'A04', :diagnosis_code => '1', :FULL_CODE => 'A041', :abbreviated_description => 'Enterotoxigenic Escherichia coli infection', :full_description => 'Enterotoxigenic Escherichia coli infection', :category_title => 'Other bacterial intestinal infections'},
#               {:category_code => 'A04', :diagnosis_code => '2', :FULL_CODE => 'A042', :abbreviated_description => 'Enteroinvasive Escherichia coli infection', :full_description => 'Enteroinvasive Escherichia coli infection', :category_title => 'Other bacterial intestinal infections'},
#               {:category_code => 'A04', :diagnosis_code => '3', :FULL_CODE => 'A043', :abbreviated_description => 'Enterohemorrhagic Escherichia coli infection', :full_description => 'Enterohemorrhagic Escherichia coli infection', :category_title => 'Other bacterial intestinal infections'},
#               {:category_code => 'A04', :diagnosis_code => '4', :FULL_CODE => 'A044', :abbreviated_description => 'Other intestinal Escherichia coli infections', :full_description => 'Other intestinal Escherichia coli infections', :category_title => 'Other bacterial intestinal infections'},
#               {:category_code => 'A04', :diagnosis_code => '5', :FULL_CODE => 'A045', :abbreviated_description => 'Campylobacter enteritis', :full_description => 'Campylobacter enteritis', :category_title => 'Other bacterial intestinal infections'},
#               {:category_code => 'A04', :diagnosis_code => '6', :FULL_CODE => 'A046', :abbreviated_description => 'Enteritis due to Yersinia enterocolitica', :full_description => 'Enteritis due to Yersinia enterocolitica', :category_title => 'Other bacterial intestinal infections'},
#               {:category_code => 'A047', :diagnosis_code => '1', :FULL_CODE => 'A0471', :abbreviated_description => 'Enterocolitis due to Clostridium difficile, recurrent', :full_description => 'Enterocolitis due to Clostridium difficile, recurrent', :category_title => 'Enterocolitis due to Clostridium difficile'},
#               {:category_code => 'A047', :diagnosis_code => '2', :FULL_CODE => 'A0472', :abbreviated_description => 'Enterocolitis d/t Clostridium difficile, not spcf as recur', :full_description => 'Enterocolitis due to Clostridium difficile, not specified as recurrent', :category_title => 'Enterocolitis due to Clostridium difficile'},
#               {:category_code => 'A048', :diagnosis_code => '', :FULL_CODE => 'A048', :abbreviated_description => 'Other specified bacterial intestinal infections', :full_description => 'Other specified bacterial intestinal infections', :category_title => 'Other specified bacterial intestinal infections'},
#               {:category_code => 'A049', :diagnosis_code => '', :FULL_CODE => 'A049', :abbreviated_description => 'Bacterial intestinal infection, unspecified', :full_description => 'Bacterial intestinal infection, unspecified', :category_title => 'Bacterial intestinal infection, unspecified'},
#               {:category_code => 'A05', :diagnosis_code => '0', :FULL_CODE => 'A050', :abbreviated_description => 'Foodborne staphylococcal intoxication', :full_description => 'Foodborne staphylococcal intoxication', :category_title => 'Other bacterial foodborne intoxications, not elsewhere classified'},
#               {:category_code => 'A05', :diagnosis_code => '1', :FULL_CODE => 'A051', :abbreviated_description => 'Botulism food poisoning', :full_description => 'Botulism food poisoning', :category_title => 'Other bacterial foodborne intoxications, not elsewhere classified'},
#               {:category_code => 'A05', :diagnosis_code => '2', :FULL_CODE => 'A052', :abbreviated_description => 'Foodborne Clostridium perfringens intoxication', :full_description => 'Foodborne Clostridium perfringens [Clostridium welchii] intoxication', :category_title => 'Other bacterial foodborne intoxications, not elsewhere classified'},
#               {:category_code => 'A05', :diagnosis_code => '3', :FULL_CODE => 'A053', :abbreviated_description => 'Foodborne Vibrio parahaemolyticus intoxication', :full_description => 'Foodborne Vibrio parahaemolyticus intoxication', :category_title => 'Other bacterial foodborne intoxications, not elsewhere classified'},
#               {:category_code => 'A05', :diagnosis_code => '4', :FULL_CODE => 'A054', :abbreviated_description => 'Foodborne Bacillus cereus intoxication', :full_description => 'Foodborne Bacillus cereus intoxication', :category_title => 'Other bacterial foodborne intoxications, not elsewhere classified'},
#               {:category_code => 'A05', :diagnosis_code => '5', :FULL_CODE => 'A055', :abbreviated_description => 'Foodborne Vibrio vulnificus intoxication', :full_description => 'Foodborne Vibrio vulnificus intoxication', :category_title => 'Other bacterial foodborne intoxications, not elsewhere classified'},
#               {:category_code => 'A05', :diagnosis_code => '8', :FULL_CODE => 'A058', :abbreviated_description => 'Other specified bacterial foodborne intoxications', :full_description => 'Other specified bacterial foodborne intoxications', :category_title => 'Other bacterial foodborne intoxications, not elsewhere classified'},
#               {:category_code => 'A05', :diagnosis_code => '9', :FULL_CODE => 'A059', :abbreviated_description => 'Bacterial foodborne intoxication, unspecified', :full_description => 'Bacterial foodborne intoxication, unspecified', :category_title => 'Other bacterial foodborne intoxications, not elsewhere classified'},
#               {:category_code => 'A06', :diagnosis_code => '0', :FULL_CODE => 'A060', :abbreviated_description => 'Acute amebic dysentery', :full_description => 'Acute amebic dysentery', :category_title => 'Amebiasis'},
#               {:category_code => 'A06', :diagnosis_code => '1', :FULL_CODE => 'A061', :abbreviated_description => 'Chronic intestinal amebiasis', :full_description => 'Chronic intestinal amebiasis', :category_title => 'Amebiasis'},
#               {:category_code => 'A06', :diagnosis_code => '2', :FULL_CODE => 'A062', :abbreviated_description => 'Amebic nondysenteric colitis', :full_description => 'Amebic nondysenteric colitis', :category_title => 'Amebiasis'},
#               {:category_code => 'A06', :diagnosis_code => '3', :FULL_CODE => 'A063', :abbreviated_description => 'Ameboma of intestine', :full_description => 'Ameboma of intestine', :category_title => 'Amebiasis'},
#               {:category_code => 'A06', :diagnosis_code => '4', :FULL_CODE => 'A064', :abbreviated_description => 'Amebic liver abscess', :full_description => 'Amebic liver abscess', :category_title => 'Amebiasis'},
#               {:category_code => 'A06', :diagnosis_code => '5', :FULL_CODE => 'A065', :abbreviated_description => 'Amebic lung abscess', :full_description => 'Amebic lung abscess', :category_title => 'Amebiasis'},
#               {:category_code => 'A06', :diagnosis_code => '6', :FULL_CODE => 'A066', :abbreviated_description => 'Amebic brain abscess', :full_description => 'Amebic brain abscess', :category_title => 'Amebiasis'},
#               {:category_code => 'A06', :diagnosis_code => '7', :FULL_CODE => 'A067', :abbreviated_description => 'Cutaneous amebiasis', :full_description => 'Cutaneous amebiasis', :category_title => 'Amebiasis'},
#               {:category_code => 'A068', :diagnosis_code => '1', :FULL_CODE => 'A0681', :abbreviated_description => 'Amebic cystitis', :full_description => 'Amebic cystitis', :category_title => 'Amebic infection of other sites'},
#               {:category_code => 'A068', :diagnosis_code => '2', :FULL_CODE => 'A0682', :abbreviated_description => 'Other amebic genitourinary infections', :full_description => 'Other amebic genitourinary infections', :category_title => 'Amebic infection of other sites'},
#               {:category_code => 'A068', :diagnosis_code => '9', :FULL_CODE => 'A0689', :abbreviated_description => 'Other amebic infections', :full_description => 'Other amebic infections', :category_title => 'Amebic infection of other sites'},
#               {:category_code => 'A069', :diagnosis_code => '', :FULL_CODE => 'A069', :abbreviated_description => 'Amebiasis, unspecified', :full_description => 'Amebiasis, unspecified', :category_title => 'Amebiasis, unspecified'},
#               {:category_code => 'A07', :diagnosis_code => '0', :FULL_CODE => 'A070', :abbreviated_description => 'Balantidiasis', :full_description => 'Balantidiasis', :category_title => 'Other protozoal intestinal diseases'},
#               {:category_code => 'A07', :diagnosis_code => '1', :FULL_CODE => 'A071', :abbreviated_description => 'Giardiasis [lambliasis]', :full_description => 'Giardiasis [lambliasis]', :category_title => 'Other protozoal intestinal diseases'},
#               {:category_code => 'A07', :diagnosis_code => '2', :FULL_CODE => 'A072', :abbreviated_description => 'Cryptosporidiosis', :full_description => 'Cryptosporidiosis', :category_title => 'Other protozoal intestinal diseases'},
#               {:category_code => 'A07', :diagnosis_code => '3', :FULL_CODE => 'A073', :abbreviated_description => 'Isosporiasis', :full_description => 'Isosporiasis', :category_title => 'Other protozoal intestinal diseases'},
#               {:category_code => 'A07', :diagnosis_code => '4', :FULL_CODE => 'A074', :abbreviated_description => 'Cyclosporiasis', :full_description => 'Cyclosporiasis', :category_title => 'Other protozoal intestinal diseases'},
#               {:category_code => 'A07', :diagnosis_code => '8', :FULL_CODE => 'A078', :abbreviated_description => 'Other specified protozoal intestinal diseases', :full_description => 'Other specified protozoal intestinal diseases', :category_title => 'Other protozoal intestinal diseases'},
#               {:category_code => 'A07', :diagnosis_code => '9', :FULL_CODE => 'A079', :abbreviated_description => 'Protozoal intestinal disease, unspecified', :full_description => 'Protozoal intestinal disease, unspecified', :category_title => 'Other protozoal intestinal diseases'},
#               {:category_code => 'A08', :diagnosis_code => '0', :FULL_CODE => 'A080', :abbreviated_description => 'Rotaviral enteritis', :full_description => 'Rotaviral enteritis', :category_title => 'Viral and other specified intestinal infections'},
#               {:category_code => 'A081', :diagnosis_code => '1', :FULL_CODE => 'A0811', :abbreviated_description => 'Acute gastroenteropathy due to Norwalk agent', :full_description => 'Acute gastroenteropathy due to Norwalk agent', :category_title => 'Acute gastroenteropathy due to Norwalk agent and other small round viruses'},
#               {:category_code => 'A081', :diagnosis_code => '9', :FULL_CODE => 'A0819', :abbreviated_description => 'Acute gastroenteropathy due to other small round viruses', :full_description => 'Acute gastroenteropathy due to other small round viruses', :category_title => 'Acute gastroenteropathy due to Norwalk agent and other small round viruses'},
#               {:category_code => 'A082', :diagnosis_code => '', :FULL_CODE => 'A082', :abbreviated_description => 'Adenoviral enteritis', :full_description => 'Adenoviral enteritis', :category_title => 'Adenoviral enteritis'},
#               {:category_code => 'A083', :diagnosis_code => '1', :FULL_CODE => 'A0831', :abbreviated_description => 'Calicivirus enteritis', :full_description => 'Calicivirus enteritis', :category_title => 'Other viral enteritis'},
#               {:category_code => 'A083', :diagnosis_code => '2', :FULL_CODE => 'A0832', :abbreviated_description => 'Astrovirus enteritis', :full_description => 'Astrovirus enteritis', :category_title => 'Other viral enteritis'},
#               {:category_code => 'A083', :diagnosis_code => '9', :FULL_CODE => 'A0839', :abbreviated_description => 'Other viral enteritis', :full_description => 'Other viral enteritis', :category_title => 'Other viral enteritis'},
#               {:category_code => 'A084', :diagnosis_code => '', :FULL_CODE => 'A084', :abbreviated_description => 'Viral intestinal infection, unspecified', :full_description => 'Viral intestinal infection, unspecified', :category_title => 'Viral intestinal infection, unspecified'},
#               {:category_code => 'A088', :diagnosis_code => '', :FULL_CODE => 'A088', :abbreviated_description => 'Other specified intestinal infections', :full_description => 'Other specified intestinal infections', :category_title => 'Other specified intestinal infections'},
#               {:category_code => 'A09', :diagnosis_code => '', :FULL_CODE => 'A09', :abbreviated_description => 'Infectious gastroenteritis and colitis, unspecified', :full_description => 'Infectious gastroenteritis and colitis, unspecified', :category_title => 'Infectious gastroenteritis and colitis, unspecified'},
#               {:category_code => 'A15', :diagnosis_code => '0', :FULL_CODE => 'A150', :abbreviated_description => 'Tuberculosis of lung', :full_description => 'Tuberculosis of lung', :category_title => 'Respiratory tuberculosis'},
#               {:category_code => 'A15', :diagnosis_code => '4', :FULL_CODE => 'A154', :abbreviated_description => 'Tuberculosis of intrathoracic lymph nodes', :full_description => 'Tuberculosis of intrathoracic lymph nodes', :category_title => 'Respiratory tuberculosis'},
#               {:category_code => 'A15', :diagnosis_code => '5', :FULL_CODE => 'A155', :abbreviated_description => 'Tuberculosis of larynx, trachea and bronchus', :full_description => 'Tuberculosis of larynx, trachea and bronchus', :category_title => 'Respiratory tuberculosis'},
#               {:category_code => 'A15', :diagnosis_code => '6', :FULL_CODE => 'A156', :abbreviated_description => 'Tuberculous pleurisy', :full_description => 'Tuberculous pleurisy', :category_title => 'Respiratory tuberculosis'},
#               {:category_code => 'A15', :diagnosis_code => '7', :FULL_CODE => 'A157', :abbreviated_description => 'Primary respiratory tuberculosis', :full_description => 'Primary respiratory tuberculosis', :category_title => 'Respiratory tuberculosis'},
#               {:category_code => 'A15', :diagnosis_code => '8', :FULL_CODE => 'A158', :abbreviated_description => 'Other respiratory tuberculosis', :full_description => 'Other respiratory tuberculosis', :category_title => 'Respiratory tuberculosis'},
#               {:category_code => 'A15', :diagnosis_code => '9', :FULL_CODE => 'A159', :abbreviated_description => 'Respiratory tuberculosis unspecified', :full_description => 'Respiratory tuberculosis unspecified', :category_title => 'Respiratory tuberculosis'},
#               {:category_code => 'A17', :diagnosis_code => '0', :FULL_CODE => 'A170', :abbreviated_description => 'Tuberculous meningitis', :full_description => 'Tuberculous meningitis', :category_title => 'Tuberculosis of nervous system'}
#             ]);


# 50.times do 
#     Patient.create(
#       fname: Faker::Name.unique.first_name,
#       lname: Faker::Name.unique.last_name,
#       gender: Faker::Gender.binary_type,
#       ssn: Faker::IDNumber.unique.valid,
#       phone: Faker::PhoneNumber.unique.cell_phone,
#       email: Faker::Internet.unique.email,
#       address_line_1: Faker::Address.street_address,
#       address_line_2: Faker::Address.secondary_address,
#       city: Faker::Address.city,
#       state: Faker::Address.state,
#       zip: Faker::Address.zip_code,
#       date_of_birth: Faker::Date.birthday(min_age: 15, max_age: 70),
#       insurId: Faker::Code.unique.nric
#     )
# end

50.times do 
  Insurance.create(
    insurance_id: Faker::Code.unique.nric,
    insured_name: Faker::Name.unique.name,
    insured_birth: Faker::Date.birthday(min_age: 15, max_age: 70),
    insured_ssn: Faker::IDNumber.unique.valid,
    insurance_start_date: Faker::Date.between(from: '2017-09-23', to: '2019-11-25'),
    insurance_end_date: Faker::Date.between(from: '2019-11-26', to: '2021-11-25'),
    insurance_limitation: Faker::Number.within(range: 50000..500000),
    insurance_deductible: Faker::Number.within(range: 1000..5000),
    insurance_copay_rate: Faker::Number.within(range: 20..50), 
    insurance_company_name: Faker::Company.unique.name,
    insurance_company_address: Faker::Address.unique.full_address,
    insurance_company_phone: Faker::PhoneNumber.cell_phone,
    insurance_company_email: Faker::Internet.unique.email,
    insurance_company_website: Faker::Internet.unique.domain_name,
    patient_id: Faker::Number.unique.within(range: 1..50)
  )
end
